
-----
Test: tests/test_scenario_1.py::test_scenario_1 (call)
Start time: 2024-11-06 21:40:42.504380
Start name method: Scenario 1 start


-----
Error occurred at: 2024-11-06 21:40:48.332644
Error: Expected URL 'https://sbis.ru/contacts/16-respublika-tatarstan?tab=clients', but got 'https://sbis.ru/contacts'
Traceback: Traceback (most recent call last):
  File "C:\Users\ajnaf\PycharmProjects\tensor_test\base\base_class.py", line 90, in assert_url
    assert get_url == result, f"Expected URL '{result}', but got '{get_url}'"
           ^^^^^^^^^^^^^^^^^
AssertionError: Expected URL 'https://sbis.ru/contacts/16-respublika-tatarstan?tab=clients', but got 'https://sbis.ru/contacts'


-----
End time: 2024-11-06 21:40:55.329692
End name method: Scenario 1 end
URL: https://tensor.ru/about

-----

-----
Test: tests/test_scenario_2.py::test_scenario_2 (call)
Start time: 2024-11-06 21:41:01.996657
Start name method: Scenario 2 start

End time: 2024-11-06 21:41:11.212247
End name method: Scenario 2 end
URL: https://sbis.ru/contacts/41-kamchatskij-kraj?tab=clients

-----
