
-----
Test: tests/test_scenario_1.py::test_scenario_1 (call)
Start time: 2024-11-07 10:32:43.015414
Start name method: Scenario 1 start

End time: 2024-11-07 10:32:58.507203
End name method: Scenario 1 end
URL: https://tensor.ru/about

-----

-----
Test: tests/test_scenario_2.py::test_scenario_2 (call)
Start time: 2024-11-07 10:33:07.735958
Start name method: Scenario 2 start

End time: 2024-11-07 10:33:18.587889
End name method: Scenario 2 end
URL: https://sbis.ru/contacts/41-kamchatskij-kraj?tab=clients

-----

-----
Test: tests/test_scenario_3.py::test_scenario_3 (call)
Start time: 2024-11-07 10:33:26.117384
Start name method: Scenario 3 start


-----
Error occurred at: 2024-11-07 10:33:33.230013
Error: Expected URL 'https://sbis.ru/download/', but got 'https://sbis.ru/download'
Traceback: Traceback (most recent call last):
  File "C:\Users\ajnaf\PycharmProjects\tensor_test\base\base_class.py", line 90, in assert_url
    assert get_url == result, f"Expected URL '{result}', but got '{get_url}'"
           ^^^^^^^^^^^^^^^^^
AssertionError: Expected URL 'https://sbis.ru/download/', but got 'https://sbis.ru/download'


-----
End time: 2024-11-07 10:33:59.422090
End name method: Scenario 3 end
URL: https://sbis.ru/download?tab=plugin&innerTab=default

-----
