
-----
Test: tests/test_scenario_1.py::test_scenario_1 (call)
Start time: 2024-11-06 14:07:56.470377
Start name method: Scenario 1 start


-----
Error occurred at: 2024-11-06 14:08:06.629575
Error: Expected URL 'https://sbis.ru/contacts/16-respublika-tatarstan?tab=clients', but got 'https://sbis.ru/contacts'
Traceback: Traceback (most recent call last):
  File "C:\Users\ajnaf\PycharmProjects\tensor_test\base\base_class.py", line 66, in assert_url
    assert get_url == result, f"Expected URL '{result}', but got '{get_url}'"
           ^^^^^^^^^^^^^^^^^
AssertionError: Expected URL 'https://sbis.ru/contacts/16-respublika-tatarstan?tab=clients', but got 'https://sbis.ru/contacts'


-----
End time: 2024-11-06 14:08:06.907397
End name method: Scenario 1 end
URL: https://sbis.ru/contacts/16-respublika-tatarstan?tab=clients

-----
