
-----
Test: tests/test_scenario_1.py::test_scenario_1 (call)
Start time: 2024-11-06 15:29:33.571779
Start name method: Scenario 1 start


-----
Error occurred at: 2024-11-06 15:29:41.746301
Error: Expected URL 'https://sbis.ru/contacts', but got 'https://sbis.ru/contacts/16-respublika-tatarstan?tab=clients'
Traceback: Traceback (most recent call last):
  File "C:\Users\ajnaf\PycharmProjects\tensor_test\base\base_class.py", line 86, in assert_url
    assert get_url == result, f"Expected URL '{result}', but got '{get_url}'"
           ^^^^^^^^^^^^^^^^^
AssertionError: Expected URL 'https://sbis.ru/contacts', but got 'https://sbis.ru/contacts/16-respublika-tatarstan?tab=clients'


-----
End time: 2024-11-06 15:29:47.866449
End name method: Scenario 1 end
URL: https://tensor.ru/about

-----
